# Generated by Django 5.2.8 on 2025-11-24 03:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('employees', 'موظف جرد'), ('supervisors', 'مشرف'), ('admins', 'مدير نظام')], max_length=20, verbose_name='الدور')),
                ('region_groups', models.ManyToManyField(blank=True, to='locations_app.regiongroup', verbose_name='الأقاليم')),
                ('regions', models.ManyToManyField(blank=True, to='locations_app.region', verbose_name='المناطق')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='اسم المستخدم')),
            ],
            options={
                'verbose_name': 'ملف المستخدم',
                'verbose_name_plural': 'ملفات المستخدمين',
            },
        ),
    ]
