# Generated by Django 5.2.8 on 2025-11-17 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'verbose_name': 'مبنى', 'verbose_name_plural': 'المباني'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'مدينة', 'verbose_name_plural': 'المدن'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'منطقة', 'verbose_name_plural': 'المناطق'},
        ),
        migrations.AlterField(
            model_name='building',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='locations_app.city', verbose_name='المدينة'),
        ),
        migrations.AlterField(
            model_name='building',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='كود المبنى'),
        ),
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(max_length=150, verbose_name='اسم المبنى'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم المدينة'),
        ),
        migrations.AlterField(
            model_name='city',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='locations_app.region', verbose_name='المنطقة'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم المنطقة'),
        ),
    ]
