# Generated by Django 5.2.8 on 2025-11-13 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_code', models.CharField(max_length=50, unique=True)),
                ('barcode', models.CharField(max_length=100, unique=True)),
                ('old_barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('main_category', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('sub_category', models.CharField(max_length=200)),
                ('status', models.CharField(default='فعال', max_length=50)),
                ('condition', models.CharField(blank=True, max_length=50, null=True)),
                ('custodian_number', models.CharField(blank=True, max_length=50, null=True)),
                ('custodian_name', models.CharField(blank=True, max_length=150, null=True)),
                ('custodian_type', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateField()),
                ('created_by_username', models.CharField(max_length=100)),
                ('building', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations_app.building')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations_app.city')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations_app.region')),
            ],
        ),
    ]
