# Generated by Django 5.2.8 on 2025-11-23 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_code', models.CharField(max_length=50, unique=True, verbose_name='رمز الأصل')),
                ('barcode', models.CharField(max_length=100, unique=True, verbose_name='الباركود')),
                ('old_barcode', models.CharField(blank=True, max_length=100, null=True, verbose_name='الباركود القديم')),
                ('description', models.TextField(verbose_name='وصف الأصل')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف')),
                ('main_category', models.CharField(max_length=100, verbose_name='الفئة الرئيسية')),
                ('type', models.CharField(max_length=100, verbose_name='النوع')),
                ('sub_category', models.CharField(max_length=200, verbose_name='الفئة الفرعية')),
                ('status', models.CharField(default='فعال', max_length=50, verbose_name='حالة الأصل')),
                ('condition', models.CharField(blank=True, max_length=50, null=True, verbose_name='حالة الاستخدام')),
                ('custodian_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم صاحب العهدة')),
                ('custodian_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='اسم صاحب العهدة')),
                ('custodian_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع العهدة')),
                ('created_at', models.DateField(verbose_name='تاريخ الإدخال')),
                ('created_by_username', models.CharField(max_length=100, verbose_name='المستخدم المدخل')),
                ('building', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations_app.building', verbose_name='المبنى')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations_app.city', verbose_name='المدينة')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations_app.region', verbose_name='المنطقة')),
            ],
            options={
                'verbose_name': 'أصل',
                'verbose_name_plural': 'الأصول',
            },
        ),
    ]
