# Generated by Django 5.2.8 on 2025-11-17 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_app', '0001_initial'),
        ('locations_app', '0002_alter_building_options_alter_city_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'verbose_name': 'أصل', 'verbose_name_plural': 'الأصول'},
        ),
        migrations.AddField(
            model_name='asset',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_code',
            field=models.CharField(max_length=50, unique=True, verbose_name='رمز الأصل'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='barcode',
            field=models.CharField(max_length=100, unique=True, verbose_name='الباركود'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations_app.building', verbose_name='المبنى'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations_app.city', verbose_name='المدينة'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='condition',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='حالة الاستخدام'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='created_at',
            field=models.DateField(verbose_name='تاريخ الإدخال'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='created_by_username',
            field=models.CharField(max_length=100, verbose_name='المستخدم المدخل'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='custodian_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='اسم صاحب العهدة'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='custodian_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم صاحب العهدة'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='custodian_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع العهدة'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='description',
            field=models.TextField(verbose_name='وصف الأصل'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='main_category',
            field=models.CharField(max_length=100, verbose_name='الفئة الرئيسية'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='old_barcode',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الباركود القديم'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations_app.region', verbose_name='المنطقة'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(default='فعال', max_length=50, verbose_name='حالة الأصل'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='sub_category',
            field=models.CharField(max_length=200, verbose_name='الفئة الفرعية'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='type',
            field=models.CharField(max_length=100, verbose_name='النوع'),
        ),
    ]
