# Generated by Django 5.2.8 on 2025-11-17 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_app', '0002_alter_asset_options_asset_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف'),
        ),
    ]
