# Generated by Django 5.2.8 on 2025-11-13 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets_app', '0001_initial'),
        ('locations_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventorySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('in_progress', 'جارية'), ('submitted_to_supervisor', 'مقدمة للمشرف'), ('supervisor_under_review', 'تحت مراجعة المشرف'), ('supervisor_approved', 'معتمدة من المشرف'), ('supervisor_rejected', 'مرفوضة من المشرف'), ('admin_approved', 'معتمدة نهائياً'), ('cancelled', 'ملغاة')], default='draft', max_length=50)),
                ('employee_comment', models.TextField(blank=True, null=True)),
                ('supervisor_comment', models.TextField(blank=True, null=True)),
                ('admin_comment', models.TextField(blank=True, null=True)),
                ('building', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations_app.building')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations_app.city')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_sessions', to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations_app.region')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('found', 'موجود'), ('missing', 'مفقود'), ('newly_added', 'مضاف جديد')], max_length=20)),
                ('scanned_at', models.DateTimeField(blank=True, null=True)),
                ('added_manually', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets_app.asset')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory_app.inventorysession')),
            ],
        ),
    ]
