# Generated by Django 5.2.8 on 2025-11-24 02:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets_app', '0001_initial'),
        ('locations_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventorySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='وقت بدء الجلسة')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='وقت انتهاء الجلسة')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('in_progress', 'جارية'), ('submitted_to_supervisor', 'مقدمة للمشرف'), ('supervisor_under_review', 'تحت مراجعة المشرف'), ('supervisor_approved', 'معتمدة من المشرف'), ('supervisor_rejected', 'مرفوضة من المشرف'), ('admin_approved', 'معتمدة نهائياً'), ('cancelled', 'ملغاة'), ('completed', 'منتهية')], default='draft', max_length=50, verbose_name='الحالة')),
                ('employee_comment', models.TextField(blank=True, null=True, verbose_name='ملاحظات الموظف')),
                ('supervisor_comment', models.TextField(blank=True, null=True, verbose_name='ملاحظات المشرف')),
                ('admin_comment', models.TextField(blank=True, null=True, verbose_name='ملاحظات مدير النظام')),
                ('building', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations_app.building', verbose_name='المبنى')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations_app.city', verbose_name='المدينة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_sessions', to=settings.AUTH_USER_MODEL, verbose_name='موظف الجرد')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations_app.region', verbose_name='المنطقة')),
                ('region_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations_app.regiongroup', verbose_name='الإقليم')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_sessions', to=settings.AUTH_USER_MODEL, verbose_name='المشرف')),
            ],
            options={
                'verbose_name': 'جلسة جرد',
                'verbose_name_plural': 'جلسات الجرد',
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=200, verbose_name='الباركود')),
                ('status', models.CharField(choices=[('found', 'موجود'), ('missing', 'مفقود'), ('new', 'أصل جديد')], default='missing', max_length=20, verbose_name='حالة الجرد')),
                ('scanned_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت المسح')),
                ('added_manually', models.BooleanField(default=False, verbose_name='أضيف يدوياً')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets_app.asset', verbose_name='الأصل')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory_app.inventorysession', verbose_name='جلسة الجرد')),
            ],
            options={
                'verbose_name': 'تفصيل جرد',
                'verbose_name_plural': 'تفاصيل الجرد',
            },
        ),
    ]
