# Generated by Django 5.2.8 on 2025-11-17 03:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_app', '0002_alter_asset_options_asset_phone_number_and_more'),
        ('inventory_app', '0001_initial'),
        ('locations_app', '0002_alter_building_options_alter_city_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'verbose_name': 'تفصيل جرد', 'verbose_name_plural': 'تفاصيل الجرد'},
        ),
        migrations.AlterModelOptions(
            name='inventorysession',
            options={'verbose_name': 'جلسة جرد', 'verbose_name_plural': 'جلسات الجرد'},
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='added_manually',
            field=models.BooleanField(default=False, verbose_name='أضيف يدوياً'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets_app.asset', verbose_name='الأصل'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='barcode',
            field=models.CharField(max_length=200, verbose_name='الباركود'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='scanned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت المسح'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory_app.inventorysession', verbose_name='جلسة الجرد'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='status',
            field=models.CharField(choices=[('found', 'موجود'), ('missing', 'مفقود'), ('new', 'أصل جديد')], default='missing', max_length=20, verbose_name='حالة الجرد'),
        ),
        migrations.AlterField(
            model_name='inventorysession',
            name='admin_comment',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات مدير النظام'),
        ),
        migrations.AlterField(
            model_name='inventorysession',
            name='building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations_app.building', verbose_name='المبنى'),
        ),
        migrations.AlterField(
            model_name='inventorysession',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations_app.city', verbose_name='المدينة'),
        ),
        migrations.AlterField(
            model_name='inventorysession',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_sessions', to=settings.AUTH_USER_MODEL, verbose_name='موظف الجرد'),
        ),
        migrations.AlterField(
            model_name='inventorysession',
            name='employee_comment',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات الموظف'),
        ),
        migrations.AlterField(
            model_name='inventorysession',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت انتهاء الجلسة'),
        ),
        migrations.AlterField(
            model_name='inventorysession',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations_app.region', verbose_name='المنطقة'),
        ),
        migrations.AlterField(
            model_name='inventorysession',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='وقت بدء الجلسة'),
        ),
        migrations.AlterField(
            model_name='inventorysession',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('in_progress', 'جارية'), ('submitted_to_supervisor', 'مقدمة للمشرف'), ('supervisor_under_review', 'تحت مراجعة المشرف'), ('supervisor_approved', 'معتمدة من المشرف'), ('supervisor_rejected', 'مرفوضة من المشرف'), ('admin_approved', 'معتمدة نهائياً'), ('cancelled', 'ملغاة'), ('completed', 'منتهية')], default='draft', max_length=50, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='inventorysession',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_sessions', to=settings.AUTH_USER_MODEL, verbose_name='المشرف'),
        ),
        migrations.AlterField(
            model_name='inventorysession',
            name='supervisor_comment',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات المشرف'),
        ),
    ]
