# Generated by Django 5.2.8 on 2025-11-24 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('table_name', models.CharField(max_length=200)),
                ('rows_count', models.IntegerField()),
                ('mode', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
